### ISSUE TITLE
New Tag Reflecting Master

### ISSUE THREAD

**Issue by jortiz2015** [goinvest/iexcloud#109]
Hello, do you mind creating a new tag to reflect the current image of Master. The tag seems to be behind and when trying to include iexcloud in go project, go mod resorts to using tag v2.15.3 . Which contains issues with annualIncomeStatements(). Thank you in advance.

**Comment by matthewrankin** [comment]
I created tag v2.16.0.

**Comment by jortiz2015** [comment]
> I created tag v2.16.0.

Thank you! @matthewrankin
