### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by matthewrankin** [goinvest/iexcloud#11]
Need to add testing—any testing, just test something!

**Comment by Redorb** [comment]
I've normally used https://github.com/h2non/gock to test my api clients, might be something to look into.

**Comment by matthewrankin** [comment]
Ok. I'll take a look.

**Comment by someone1** [comment]
FYI - I was testing using the sandbox URI and as the responses come back scrambled, some of the code in the package errors out (e.g. the issue type for Company responses). Might be worth considering changing behavior like this so the sandbox can be used for testing.

**Comment by lfaoro** [comment]
how would we add testing? I don't think mocking every endpoint is a good idea as they evolve and change and the test should pick that up.

we need a sandbox account w/ api key that allows for live testing, can you ask IEX to provide us one?

**Comment by matthewrankin** [comment]
IEX Cloud provides all accounts with a sandbox for testing.

https://iexcloud.io/docs/api/#testing-sandbox
