### ISSUE TITLE
Quote.DelayedTime versus Quote.DelayedPriceTime

### ISSUE THREAD

**Issue by fabianbaier** [goinvest/iexcloud#14]
According to the api reference https://iexcloud.io/docs/api/#quote it should be named `delayedPriceTime` but the json tag for https://github.com/goinvest/iexcloud/blob/master/stocks.go#L346 is `delayedTime`.

Looking at https://github.com/goinvest/iexcloud/blob/master/stocks.go#L350 I see the right naming convention applied which makes me wonder if that is just a typo or what is expressed with `delayedTime`.

For now it looks like we should rename it to:

```
	DelayedPriceTime           string     `json:"delayedPriceTime"`
```

Thoughts?

**Comment by matthewrankin** [comment]
I agree it should be renamed.
