### ISSUE TITLE
SSE Support

### ISSUE THREAD

**Issue by kenanwarren** [goinvest/iexcloud#21]
Hope you don't mind me opening an issue so I can track supporting this. I might give it a crack this weekend. Some references:
https://iexcloud.io/docs/api/#streaming
https://github.com/r3labs/sse

**Comment by matthewrankin** [comment]
I don't mind at all. Feel free to open issues as you see fit. Thanks for your contributions!

**Comment by redorb** [comment]
No problem, thanks for being a good steward for the repo!

**Comment by matthiasak** [comment]
According to the README in master:

`Real-time Quote — Use Quote.`

By Real-time, do we mean intraday? Or do we mean "SSE"?
