### ISSUE TITLE
[Feature Request] Context aware calls

### ISSUE THREAD

**Issue by someone1** [goinvest/iexcloud#22]
Using the `context` package is (becoming) idiomatic when creating libraries making any sort of RPC/HTTP calls such as this one. Would it be possible to add Context aware versions of each call? This enables things such as timeouts, cancellation, and tracing among other potential use-cases.

**Comment by matthewrankin** [comment]
Good thought. Let me see what I can do.

**Comment by someone1** [comment]
@matthewrankin - I can put some developer resources on this, what are your thoughts on how to tackle this? 

1. Create `WithContext` versions of each call (no breaking changes)? 
2. Update each call to take a context (breaking change)?
3. Update each call to take a context in a v2 branch (go modules versioning)?

**Comment by matthewrankin** [comment]
I'm open to ideas. I think I'd prefer either option 1 or 3. Do you have a preference? Does anyone else want to weigh in on this?

**Comment by someone1** [comment]
I think option 3 is the way to go - I can have my team give a PR this week with the changes.

Thank you!

**Comment by matthewrankin** [comment]
@someone1 Sounds great. Thanks.

**Comment by DerekDuchesne** [comment]
Could you tag the latest commit to the v2 branch with "2.0.0"?

Thanks!

**Comment by matthewrankin** [comment]
@DerekDuchesne Done.

**Comment by DerekDuchesne** [comment]
Yes, I think this issue can be closed.

Thanks!
