### ISSUE TITLE
Move v2 development to master branch

### ISSUE THREAD

**Issue by matthewrankin** [goinvest/iexcloud#30]
I'm thinking about moving the head of master to a v1 branch and moving the v2 branch development to the master branch. I'd like to add some features, and I was thinking I'd only add them to v2 instead of continuing to support v1 and v2 (the primary difference being that v2 calls are context-aware). Thoughts?

**Comment by someone1** [comment]
This is a fair approach though I guess I am biased 😄

**Comment by matthewrankin** [comment]
Branch v2 has been merged into master and a v1 branch has been created. New development for the v2 branch will be performed on the master branch. Closes in 90a5ec4.
