### ISSUE TITLE
error retrieving dividends data

### ISSUE THREAD

**Issue by vglafirov** [goinvest/iexcloud#41]
Following code throws an error:
`			div, err := Client.Dividends("msft", "1y")
			if err != nil {
				return err
			}
`
`json: cannot unmarshal string into Go struct field Dividend.amount of type float64`

API returns Dividends.Amount in string format, but it should be float64
`curl https://sandbox.iexapis.com/stable/stock/msft/dividends/1y?token=Tsk_2741005850514d079250709354fad711                                                                                                             
[{"exDate":"2019-02-28","paymentDate":"2019-03-24","recordDate":"2019-03-01","declaredDate":"2018-12-07","amount":"0.47","flag":"shaC","currency":"USD","description":"Srs rriehOdnaya","frequency":"tryerlauq","date":"2019-11-17"}]`

**Comment by cohenjo** [comment]
Ya, a conversion should be add:
https://github.com/goinvest/iexcloud/blob/2740cd5af52d81c6d0517bb803d7814b2be6279f/stocks.go#L195
It should be:
```	
Amount       float64 `json:"amount,string"`
```
