### ISSUE TITLE
intraday endpoint support

### ISSUE THREAD

**Issue by ajsharp** [goinvest/iexcloud#54]
Requesting support for the [intraday prices](https://iexcloud.io/docs/api/#intraday-prices) endpoint. At first glance, it looks like the underlying data structures exist in this repo already.

**Comment by matthewrankin** [comment]
Added the following method for intraday prices (closed in commit 87c53229014d5c865a96a1668ecc7183a050741d).

```
func (c Client) IntradayPrices(ctx context.Context, symbol string) ([]IntradayPrice, error)
```
