### ISSUE TITLE
[BUG]- HistoricalPricesPerDay and IntradayhistoricalPricesPerday implementations are switched

### ISSUE THREAD

**Issue by judearavinda** [goinvest/iexcloud#68]
https://github.com/goinvest/iexcloud/blob/39ebeebfdfcd210eb480fc12d51f302be4d9f6ea/client.go#L268

In the docs of https://iexcloud.io/docs/api/#historical-prices, it states that only when you combine this with chartByDay=true this returns historical OHLCV data for that date. Otherwise, it returns data by minute for a specified date, if available. Therefore your implementations are switched. For HistoricalPricesByDay u need the chartByDay parameter. For IntradayHistoricalPricesByDay, you ignore it. Verified in sandbox and prod environments.

**Comment by matthewrankin** [comment]
@judearavinda Thanks.
