### ISSUE TITLE
HistoricalDataPoint volume is an int, but should be float64 (JSON unmarshall error)

### ISSUE THREAD

**Issue by 0x-2a** [goinvest/iexcloud#74]
`HistoricalDataPoint` volumes can be non-integer... See https://sandbox.iexapis.com/stable/stock/aht/batch?types=chart&range=5y&token=Tsk_0d9460b788a04e189e5141a5f1b2c124 (or the prod equivalent).

See https://github.com/goinvest/iexcloud/blob/master/historical.go#L53, should be `float64`.

**Comment by matthewrankin** [comment]
Closed in commit 00cfc05.
