### ISSUE TITLE
Add FIGI and CIK fields to Symbol

### ISSUE THREAD

**Issue by gganley** [goinvest/iexcloud#79]
Per the [2020 Data Upgrade](https://intercom.help/iexcloud/en/articles/4529082-iex-cloud-s-2020-data-upgrade) article `iexID` is being deprecated in favor of FIGI and CIK. Should just be able to add those fields.

> The "iexID" field will be deprecated in 2021. We’re developing a comprehensive reference data model for early 2021, which will expand the number of identifiers you can use to query data on the platform. As a part of this update, we will ultimately retire the use of iexID as a symbol identifier in early 2021. To give you more time to migrate from its usage, we’ve temporarily restored access to iexID. In the interim, we suggest migrating to the use of FIGI as an identifier for stocks and ETFs, or CIK for mutual funds. Our team will keep you up to date on timelines for introducing new identifiers and fully moving away from iexID, so that you can prepare accordingly.

**Comment by rsuttles58** [comment]
I would be happy to add these fields to the appropriate structs.  Can any project admins let me know if this is a change that you would like to see built out?

**Comment by matthewrankin** [comment]
@rsuttles58 Yes, I'd greatly appreciate your help.

**Comment by lfaoro** [comment]
@rsuttles58 how's the change going, did you find the time to effect it?

**Comment by matthewrankin** [comment]
Closed by commit 7cd26ca and commit 6e42333.
