### ISSUE TITLE
U.S. Holidays and Trading Dates endpoint

### ISSUE THREAD

**Issue by TheStu** [goinvest/iexcloud#87]
I'm looking to use the U.S. Holidays and Trading Dates endpoint (https://iexcloud.io/docs/api/#u-s-holidays-and-trading-dates). This library has 6 different functions (https://github.com/goinvest/iexcloud/blob/87be4c7ce08aacd830355029e8f34bbc9174549c/client.go#L1252) that hit that endpoint, but they're all opinionated on what parameters I should be putting in. There's no function that lets me just set all the parameters myself. Is that an intentional choice? If I submitted a PR that just lets the programmer set all the parameters, would it be accepted?

**Comment by matthewrankin** [comment]
@TheStu — Yes, I'm open to pull requests. What if we added the following methods:

```go
func (c Client) Holidays(ctx context.Context, dir string, last int, startDate Date) ([]TradeHolidayDate, error)
func (c Client) TradingDays(ctx context.Context, dir string, last int, startDate Date) ([]TradeHolidayDate, error)
```

I'm torn between making `dir` a string or making it an enum, since this can only be `next` or `last`. Do you want to code this up into a PR?

**Comment by TheStu** [comment]
I think leaving it as a string makes sense ... let the API return an error if a wrong value is passed through.

https://github.com/goinvest/iexcloud/pull/88
